# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
name: Build and Test
trigger:
  branches:
    include:
      - master
      - prod
      - main

pr:
  branches:
    include:
      - master
      - prod
      - main

pool:
  vmImage: "ubuntu-latest"
strategy:
  matrix:
    Python38:
      python.version: "3.8"

steps:
  - task: UsePythonVersion@0

    inputs:
      versionSpec: "$(python.version)"
    displayName: "Use Python $(python.version)"

  - script: |
      python -m pip install --upgrade pip
      pip install .
    displayName: "Install dependencies"

  - script: |
      pip install -r requirements.txt
      black --check .
      mypy .
    displayName: "Lint"

  - script: |
      pytest
    displayName: "pytest"
