name: Update Dependencies

on:
  push:
    branches:
      - main

  schedule:
    - cron: "5 6 * * 1-5"

  workflow_dispatch:

jobs:
  compile-requirements:
    uses: equinor/armada/.github/workflows/compile_python_requirements_and_create_pr.yml@main
    permissions:
      contents: write
      pull-requests: write
