on:
  push:
    branches:
      - main
      - update-dependencies
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies with the compiled requirements (for Python 3.12)
        if: ${{matrix.python-version == '3.12'}}
        run: |
          pip install -r requirements.txt -e .[dev]

      - name: Install dependencies based on the pyproject.toml file (for older Python versions)
        if: ${{matrix.python-version != '3.12'}}
        run: |
          pip install -e .[dev]

      - name: Test with pytest
        run: |
          pytest

      - name: Lint
        run: |
          black --check .
          mypy .
