name: Test and lint python package

on:
  push:
    branches:
      - main
      - update-dependencies
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-and-lint:
    uses: equinor/armada/.github/workflows/test_and_lint_python_package.yml@main
    with:
      python-versions: '["3.14"]'
      run-ruff: false
      run-isort: false
